services:
  postgres-shard-0:
    image: postgres:18-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 4dm1n
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: poc-db
    volumes:
      - postgres_shard_0_data:/var/lib/postgresql/data

  postgres-shard-1:
    image: postgres:18-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: 4dm1n
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: poc-db
    volumes:
      - postgres_shard_1_data:/var/lib/postgresql/data

volumes:
  postgres_shard_0_data:
  postgres_shard_1_data: